# .github/workflows/ci.yml (steps section)
steps:
  - uses: actions/checkout@v4

  - uses: actions/setup-python@v5
    with:
      python-version: "3.11"

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Train (deterministic)
    run: python training/train.py --out-dir artifacts --model-version ${{ github.sha }}

  - name: Tests
    run: pytest -q

  - name: Lint (ruff)
    run: ruff check .

  - name: Style (black)
    run: black --check .

  - name: Upload artifacts
    uses: actions/upload-artifact@v4
    with:
      name: model-artifacts
      path: artifacts/
      if-no-files-found: error

